name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Prepare artifact
      run: mkdir ./artifact/BepInEx/plugins ./artifact/BepInEx/patchers |
        cp ./SixDash/bin/**/SixDash.*l ./artifact/BepInEx/plugins |
        cp ./SixDash.Patcher/bin/**/SixDash.Patcher.dll ./artifact/BepInEx/patchers |
        cp ./meta/* ./artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: SixDash-latest
        path: artifact
