name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Prepare artifact
      run: |
        mkdir -p artifact/BepInEx/plugins artifact/BepInEx/patchers artifact/3Dash_Data/StreamingAssets
        cp ./SixDash/bin/Release/netstandard2.1/SixDash.dll ./SixDash/bin/Release/netstandard2.1/SixDash.xml ./artifact/BepInEx/plugins
        cp ./SixDash.Patcher/bin/Release/net35/SixDash.Patcher.dll ./artifact/BepInEx/patchers
        cp ./assets/6dash ./artifact/3Dash_Data/StreamingAssets
        cp ./meta/icon.png ./meta/manifest.json ./meta/README.md ./artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: SixDash-latest
        path: artifact
